# Use the official Node.js image as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the contents of your application directory into the container
COPY . /app

# Set the NODE_CONFIG_DIR environment variable
ENV NODE_CONFIG_DIR /app/config

# Install the project dependencies
RUN NODE_ENV=production npm install

# Expose a port that the app will run on
EXPOSE 4000

# Command to start the express server
CMD ["node","server.js"]

# docker buildx build --platform linux/amd64 -t server .